/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DatabaseConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import model.TaiKhoan;

/**
 *
 * @author chanh
 */
public class pnlHangHoa extends javax.swing.JPanel {

    /**
     * Creates new form pnlHangHoa
     */
    
    private TaiKhoan taiKhoan;
    
    public void capnhatTable() {
        loadTableData(taiKhoan);
    }
    
    private void filterTable(String query) {
        DefaultTableModel model = (DefaultTableModel) tblHangHoa.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        tblHangHoa.setRowSorter(sorter);

        if (query.trim().isEmpty()) {
            sorter.setRowFilter(null); // Nếu ô tìm kiếm trống, hiển thị tất cả dữ liệu
        } else {
            // Lọc dữ liệu dựa trên chuỗi tìm kiếm, không phân biệt chữ hoa/thường
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }
    }
    
    private void loadTableData(TaiKhoan taiKhoan) {
        DefaultTableModel model = (DefaultTableModel) tblHangHoa.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        tblHangHoa.setRowSorter(sorter);
        model.setRowCount(0); // Xóa dữ liệu cũ trên bảng

        try (Connection conn = new DatabaseConnection().getConnection()) {
            String sql = "SELECT MaHang, TenHang, SoLuongTon, DonViTinh, DonGia, MoTa, NhaSanXuat FROM HangHoa WHERE ID_TaiKhoan = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, taiKhoan.getID_TaiKhoan());
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getString("MaHang"),
                    rs.getString("TenHang"),
                    rs.getInt("SoLuongTon"),
                    rs.getString("DonViTinh"),
                    rs.getFloat("DonGia"),
                    rs.getString("MoTa"),
                    rs.getString("NhaSanXuat")
                };
                model.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Không thể tải dữ liệu từ cơ sở dữ liệu 2!");
        }
    }
    
    public pnlHangHoa(TaiKhoan taiKhoan){
        initComponents();
        this.taiKhoan = taiKhoan;
        
        // Thêm DocumentListener cho ô tìm kiếm
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }
        });
        
        loadTableData(taiKhoan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        btnThemHangHoa = new javax.swing.JButton();
        btnSuaHangHoa = new javax.swing.JButton();
        btnXoaHangHoa = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng hóa", "Tên hàng hóa", "Số lượng tồn", "Đơn vị tính", "Đơn giá", "Mô tả", "Nhà sản xuất"
            }
        ));
        jScrollPane1.setViewportView(tblHangHoa);

        btnThemHangHoa.setText("Thêm hàng hóa");
        btnThemHangHoa.setPreferredSize(new java.awt.Dimension(150, 35));
        btnThemHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHangHoaActionPerformed(evt);
            }
        });

        btnSuaHangHoa.setText("Sửa thông tin");
        btnSuaHangHoa.setPreferredSize(new java.awt.Dimension(150, 35));
        btnSuaHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHangHoaActionPerformed(evt);
            }
        });

        btnXoaHangHoa.setText("Xóa hàng hóa");
        btnXoaHangHoa.setPreferredSize(new java.awt.Dimension(150, 35));
        btnXoaHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHangHoaActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setPreferredSize(new java.awt.Dimension(150, 35));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        jLabel1.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuaHangHoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaHangHoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimKiem)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHangHoaActionPerformed
        HH_Them themForm = new HH_Them(taiKhoan);
        themForm.setVisible(true);
        
        themForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadTableData(taiKhoan);
            }
        });
    }//GEN-LAST:event_btnThemHangHoaActionPerformed

    private void btnSuaHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHangHoaActionPerformed
        int selectedRow = tblHangHoa.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng hóa để sửa!");
            return;
        }

        // Lấy thông tin
        String maHH = tblHangHoa.getValueAt(selectedRow, 0).toString();
        String tenHH = tblHangHoa.getValueAt(selectedRow, 1).toString();
        int soluongTon = Integer.parseInt(tblHangHoa.getValueAt(selectedRow, 2).toString());
        String donviTinh = tblHangHoa.getValueAt(selectedRow, 3).toString();
        float donGia = Float.parseFloat(tblHangHoa.getValueAt(selectedRow, 4).toString());
        String moTa = tblHangHoa.getValueAt(selectedRow, 5).toString();
        String nhaSanXXuat = tblHangHoa.getValueAt(selectedRow, 6).toString();

        HH_Sua suaForm = new HH_Sua(taiKhoan, maHH, tenHH, soluongTon, donviTinh, donGia, moTa, nhaSanXXuat);
        suaForm.setVisible(true);
        
        suaForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                loadTableData(taiKhoan); // Cập nhật lại bảng sau khi sửa
            }
        });
    }//GEN-LAST:event_btnSuaHangHoaActionPerformed

    private void btnXoaHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHangHoaActionPerformed
        int selectedRow = tblHangHoa.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng hóa để xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa hàng hóa này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String maHH = tblHangHoa.getValueAt(selectedRow, 0).toString();

            try (Connection conn = new DatabaseConnection().getConnection()) {
                String sql = "DELETE FROM HangHoa WHERE MaHang = ? AND ID_TaiKhoan = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maHH);
                ps.setInt(2, taiKhoan.getID_TaiKhoan());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadTableData(taiKhoan); // Cập nhật lại bảng sau khi xóa
            } catch (Exception ex) {
                Logger.getLogger(pnlNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnXoaHangHoaActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose(); // Đóng form chính
            new Login().setVisible(true); // Hiển thị form đăng nhập
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnSuaHangHoa;
    private javax.swing.JButton btnThemHangHoa;
    private javax.swing.JButton btnXoaHangHoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
