/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DatabaseConnection;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import model.TaiKhoan;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author chanh
 */
public class pnlPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form pnlPhieuNhap
     */
    
    private TaiKhoan taiKhoan;
    
    private void filterTable(String query) {
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        tblPhieuNhap.setRowSorter(sorter);

        if (query.trim().isEmpty()) {
            sorter.setRowFilter(null); // Nếu ô tìm kiếm trống, hiển thị tất cả dữ liệu
        } else {
            // Lọc dữ liệu dựa trên chuỗi tìm kiếm, không phân biệt chữ hoa/thường
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }
    }
    
    private void loadTableData(TaiKhoan taiKhoan) {
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        tblPhieuNhap.setRowSorter(sorter);
        model.setRowCount(0); // Xóa dữ liệu cũ trên bảng

        try (Connection conn = new DatabaseConnection().getConnection()) {
            String sql = "SELECT MaPhieuNhap, NgayNhap, MaNhanVien, NhaCungCap, MaHang, SoLuongNhap FROM PhieuNhap WHERE ID_TaiKhoan = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, taiKhoan.getID_TaiKhoan());
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String maPhieu = rs.getString("MaPhieuNhap");
                Date ngayNhap = rs.getDate("NgayNhap");
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String ngayNhap1 = sdf.format(ngayNhap);
                String maNhanVien = rs.getString("MaNhanVien");
                String nhaCungCap = rs.getString("NhaCungCap");
                String maHang = rs.getString("MaHang");
                int soLuongNhap = rs.getInt("SoLuongNhap");
                
                Object[] row = {maPhieu, ngayNhap1, maNhanVien, nhaCungCap, maHang, soLuongNhap};
                model.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Không thể tải dữ liệu từ cơ sở dữ liệu 3!");
        }
    }
    
    public pnlPhieuNhap(TaiKhoan taiKhoan){
        initComponents();
        this.taiKhoan = taiKhoan;
        
        DefaultTableModel model = new DefaultTableModel();
        tblPhieuNhap.setModel(model);
        model.addColumn("Mã phiếu");
        model.addColumn("Ngày nhập");
        model.addColumn("Mã nhân viên");
        model.addColumn("Nhà cung cấp");
        model.addColumn("Mã hàng");
        model.addColumn("Số lượng nhập");
        
        // Thêm DocumentListener cho ô tìm kiếm
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable(txtTimKiem.getText());
            }
        });
        
        loadTableData(taiKhoan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnDangXuat = new javax.swing.JButton();
        btnXoaPhieuNhap = new javax.swing.JButton();
        btnSuaPhieuNhap = new javax.swing.JButton();
        btnThemPhieuNhap = new javax.swing.JButton();

        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Ngày nhập", "Mã nhân viên", "Nhà cung cấp", "Mã hàng hóa", "Số lượng nhập"
            }
        ));
        jScrollPane1.setViewportView(tblPhieuNhap);

        jLabel1.setText("Tìm kiếm:");

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setPreferredSize(new java.awt.Dimension(150, 35));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnXoaPhieuNhap.setText("Xóa phiếu nhập");
        btnXoaPhieuNhap.setPreferredSize(new java.awt.Dimension(150, 35));
        btnXoaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuNhapActionPerformed(evt);
            }
        });

        btnSuaPhieuNhap.setText("Sửa thông tin");
        btnSuaPhieuNhap.setPreferredSize(new java.awt.Dimension(150, 35));
        btnSuaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPhieuNhapActionPerformed(evt);
            }
        });

        btnThemPhieuNhap.setText("Thêm phiếu nhập");
        btnThemPhieuNhap.setPreferredSize(new java.awt.Dimension(150, 35));
        btnThemPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnThemPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSuaPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuNhapActionPerformed
        PN_Them themForm = new PN_Them(taiKhoan);
        themForm.setVisible(true);
        
        themForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadTableData(taiKhoan);
            }
        });
    }//GEN-LAST:event_btnThemPhieuNhapActionPerformed

    private void btnSuaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPhieuNhapActionPerformed
        int selectedRow = tblPhieuNhap.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phiếu nhập để sửa!");
            return;
        }

        // Lấy thông tin
        String phieuNhap = tblPhieuNhap.getValueAt(selectedRow, 0).toString();
        String ngayNhap1 = tblPhieuNhap.getValueAt(selectedRow, 1).toString();
        String maNhanVien = tblPhieuNhap.getValueAt(selectedRow, 2).toString();
        String nhaCungCap= tblPhieuNhap.getValueAt(selectedRow, 3).toString();
        String maHang = tblPhieuNhap.getValueAt(selectedRow, 4).toString();
        int soluongNhap = Integer.parseInt(tblPhieuNhap.getValueAt(selectedRow, 5).toString());
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date ngayNhap = null;
        try {
            ngayNhap = sdf.parse(ngayNhap1);
        } catch (ParseException ex) {
            Logger.getLogger(pnlPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }

        PN_Sua suaForm = new PN_Sua(taiKhoan, phieuNhap, ngayNhap, maNhanVien, nhaCungCap, maHang, soluongNhap);
        suaForm.setVisible(true);
        
        suaForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                loadTableData(taiKhoan); // Cập nhật lại bảng sau khi sửa
            }
        });
    }//GEN-LAST:event_btnSuaPhieuNhapActionPerformed

    private void btnXoaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuNhapActionPerformed
        int selectedRow = tblPhieuNhap.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phiếu nhập để xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa phiếu nhập này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String maPN = tblPhieuNhap.getValueAt(selectedRow, 0).toString();
            String maNV = tblPhieuNhap.getValueAt(selectedRow, 2).toString();
            String maHH = tblPhieuNhap.getValueAt(selectedRow, 4).toString();
            int soluongNhap = Integer.parseInt(tblPhieuNhap.getValueAt(selectedRow, 5).toString());

            try (Connection conn = new DatabaseConnection().getConnection()) {
                String sql = "DELETE FROM PhieuNhap WHERE MaPhieuNhap = ? AND MaNhanVien = ? AND MaHang = ? AND ID_TaiKhoan = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, maPN);
                ps.setString(2, maNV);
                ps.setString(3, maHH);
                ps.setInt(4, taiKhoan.getID_TaiKhoan());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadTableData(taiKhoan); // Cập nhật lại bảng sau khi xóa
            } catch (Exception ex) {
                Logger.getLogger(pnlNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnXoaPhieuNhapActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose(); // Đóng form chính
            new Login().setVisible(true); // Hiển thị form đăng nhập
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnSuaPhieuNhap;
    private javax.swing.JButton btnThemPhieuNhap;
    private javax.swing.JButton btnXoaPhieuNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
