/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DatabaseConnection;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author chanh
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTen_TaiKhoan = new javax.swing.JTextField();
        lbTen_TaiKhoan = new javax.swing.JLabel();
        lbMatKhau_TaiKhoan = new javax.swing.JLabel();
        txtMatKhau_TaiKhoan = new javax.swing.JPasswordField();
        rdHienthi_MatKhau = new javax.swing.JRadioButton();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNhapLaiMatKhau_TaiKhoan = new javax.swing.JLabel();
        txtNhapLaiMatKhau_TaiKhoan = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng ký");

        lbTen_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTen_TaiKhoan.setText("Tên đăng nhập:");

        lbMatKhau_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMatKhau_TaiKhoan.setText("Mật khẩu:");

        rdHienthi_MatKhau.setText("Hiển thị mật khẩu");
        rdHienthi_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHienthi_MatKhauActionPerformed(evt);
            }
        });

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setMaximumSize(new java.awt.Dimension(100, 23));
        btnDangNhap.setMinimumSize(new java.awt.Dimension(100, 23));
        btnDangNhap.setPreferredSize(new java.awt.Dimension(100, 35));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.setMaximumSize(new java.awt.Dimension(100, 23));
        btnDangKy.setMinimumSize(new java.awt.Dimension(100, 23));
        btnDangKy.setPreferredSize(new java.awt.Dimension(100, 35));
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 195, 246));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHO HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        lbNhapLaiMatKhau_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNhapLaiMatKhau_TaiKhoan.setText("Xác nhận mật khẩu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTen_TaiKhoan)
                                    .addComponent(lbMatKhau_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatKhau_TaiKhoan)
                                    .addComponent(txtTen_TaiKhoan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNhapLaiMatKhau_TaiKhoan)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdHienthi_MatKhau)
                                    .addComponent(txtNhapLaiMatKhau_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTen_TaiKhoan)
                    .addComponent(txtTen_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau_TaiKhoan)
                    .addComponent(txtMatKhau_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNhapLaiMatKhau_TaiKhoan)
                    .addComponent(txtNhapLaiMatKhau_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdHienthi_MatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdHienthi_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHienthi_MatKhauActionPerformed
        if(rdHienthi_MatKhau.isSelected()){
            txtMatKhau_TaiKhoan.setEchoChar((char) 0); // Hien thi mat khau bang cach dat echoChar la 0
            txtNhapLaiMatKhau_TaiKhoan.setEchoChar((char) 0);
        }
        else{
            txtMatKhau_TaiKhoan.setEchoChar('*'); // An mat khau bang dau *
            txtNhapLaiMatKhau_TaiKhoan.setEchoChar('*');
        }
    }//GEN-LAST:event_rdHienthi_MatKhauActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        String tenTK = txtTen_TaiKhoan.getText();
        String mkTK = txtMatKhau_TaiKhoan.getText();
        String mklTK = txtNhapLaiMatKhau_TaiKhoan.getText();
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            ArrayList<String> dsTen_TaiKhoan = new ArrayList<>();
            conn = new DatabaseConnection().getConnection();
            String sql1 = "select Ten_TaiKhoan from TaiKhoan";
            try {
                ps = conn.prepareStatement(sql1);
                rs = ps.executeQuery();
                while (rs.next()) {
                    String Ten_TaiKhoan = rs.getString("Ten_TaiKhoan");
                    dsTen_TaiKhoan.add(Ten_TaiKhoan);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            if(tenTK.isEmpty() || mkTK.isEmpty() || mklTK.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Bạn cần nhập đủ thông tin!", "Message", JOptionPane.WARNING_MESSAGE);
                throw new Exception("Lỗi bỏ trống thông tin");
            }
            else if(dsTen_TaiKhoan.contains(tenTK)){
                JOptionPane.showConfirmDialog(this, "Tên đăng nhập đã được sử dụng!", "Message", JOptionPane.WARNING_MESSAGE);
                throw new Exception("Lỗi trùng tên đăng nhập");
            }
            else if(!mkTK.equals(mklTK)){
                JOptionPane.showConfirmDialog(this, "Mật khẩu nhập lại không đúng", "Message", JOptionPane.WARNING_MESSAGE);
            }
            else{
                String sql = "insert into TaiKhoan(Ten_TaiKhoan, MatKhau_TaiKhoan) values (?, ?)";
                ps = conn.prepareStatement(sql);
                ps.setString(1, tenTK);
                ps.setString(2, mkTK);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đăng ký thành công", "Message", JOptionPane.INFORMATION_MESSAGE);
                new Login().setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMatKhau_TaiKhoan;
    private javax.swing.JLabel lbNhapLaiMatKhau_TaiKhoan;
    private javax.swing.JLabel lbTen_TaiKhoan;
    private javax.swing.JRadioButton rdHienthi_MatKhau;
    private javax.swing.JPasswordField txtMatKhau_TaiKhoan;
    private javax.swing.JPasswordField txtNhapLaiMatKhau_TaiKhoan;
    private javax.swing.JTextField txtTen_TaiKhoan;
    // End of variables declaration//GEN-END:variables
}
